"""add mode and generation_task_id to wizard_sessions

Revision ID: dbfcd3a42cc2
Revises: e85e2f477e69
Create Date: 2026-03-25 11:25:17.930011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfcd3a42cc2'
down_revision: Union[str, Sequence[str], None] = 'e85e2f477e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wizard_sessions', sa.Column('mode', sa.String(length=20), nullable=True))
    op.add_column('wizard_sessions', sa.Column('generation_task_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wizard_sessions', 'generation_task_id')
    op.drop_column('wizard_sessions', 'mode')
    # ### end Alembic commands ###
